robot_id: ropod_001
config_dirs:
    hardware: component_monitoring/component_config/robot/hardware
    software: component_monitoring/component_config/robot/software
recovery_config: component_monitoring/component_config/robot/recovery_config.yaml
robot_store_interface:
    db_name: robot_store
    component_collection_name: components
    monitor_collection_name: status
    db_port: 27017
status_communication:
    zyre_groups: ['MONITOR']
black_box:
    id: black_box_001
    zyre_node_name: component_monitoring_query_node_ropod_001
    zyre_groups: ['MONITOR', 'ROPOD']
